name: random-persons-workflow

on:
  push:
    branches: none #main
  pull_request:
    branches: none #main

  workflow_dispatch: # temporary for testing

jobs:
  trigger-workflow-own:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run my repo workflow
        run: echo 'this repo workflows'

  trigger-workflow-remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    uses: ph-codific/pdf-generator/.github/workflows/symfony.yml@main
    with:
      keep_alive: 1
      url: https://github.com/owaspsamm/i18n-FR.git
      branch: trans_2.0
      model: model
      language: fr
