name: random-persons-workflow

on:
  push:
    branches: none #main
  pull_request:
    branches: none #main

  workflow_dispatch: # temporary for testing
    inputs:
      keep_alive:
        description: 'docker keep alive'
        required: true
        default: 1
      url:
        description: 'The url of the repo'
        required: true
        default: https://github.com/owaspsamm/i18n-FR.git
      branch:
        description: 'branch of the repo'
        required: true
        default: trans_2.0
      model:
        description: 'the model'
        required: true
        default: model
      language:
        description: 'the language'
        default: fr

jobs:
  trigger-workflow-own:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run my repo workflow
        run: echo 'this repo workflows'

  trigger-workflow-remote:
    runs-on: ubuntu-latest
    needs: trigger-workflow-own
    steps:
      - name: Run remote workflow
        uses: https://github.com/ph-codific/pdf-generator/blob/main/.github/workflows/symfony.yml@main
        with:
          keep_alive: 1
          url: https://github.com/owaspsamm/i18n-FR.git
          branch: trans_2.0
          model: model
          language: fr
