name: Listen for pushes in original repository

on:
  push:
    branches:
      - main
      - trans_2.0

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run my repo workflow
        run: echo 'this repo workflows'

  pdf-generate-workflow:
    runs-on: ubuntu-latest
    needs: trigger-workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run pdf workflow
        uses: ph-codific/pdf-generator@translations
        with:
          keep_alive: 1
          url: https://github.com/owaspsamm/i18n-FR.git
          branch: trans_2.0
          model: model
          language: fr
          docker-image: php:8.1
